"""FS-F2 validation: phantom truth, analytical oracle, external nanite
overlap, failure witnesses, reliability determinism and real-data
characterization.

Every assertion here is a scientific claim about the FS-F2 force-mechanics
stack: frozen equations, honest recovery tolerances (contact-precision
limited), typed failure paths and deterministic reliability estimates.
"""

from __future__ import annotations

import json
import math
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "force_mechanics"
NANITE_DIR = (
    Path(__file__).resolve().parents[2] / ".reference" / "force-spectroscopy" / "nanite-reference"
)
sys.path.insert(0, str(FIXTURE_DIR))

from generate_mech_phantoms import K_SPRING, generate_phantoms  # noqa: E402
from oracle_mechanics_analytical import (  # noqa: E402
    forward_dmt,
    forward_hertz,
    forward_jkr,
    forward_punch,
    forward_sneddon,
)

from spmkit.core.analysis import (  # noqa: E402
    ForceFoundationError,
    ForceMechanicsError,
    compare_contact_models,
    compute_indentation,
    prepare_force_curve,
    select_contact_fit_window,
)
from spmkit.core.analysis.force_mechanics import (  # noqa: E402
    analyze_force_fit_sensitivity,
    bootstrap_force_fit,
    diagnose_force_fit,
    fit_dmt,
    fit_flat_punch,
    fit_force_volume_mechanics,
    fit_hertz_sphere,
    fit_jkr,
    fit_sneddon_cone,
    forward_model,
)
from spmkit.core.models import (  # noqa: E402
    Calibration,
    ForceCurve,
    ForceSegment,
    ForceVolume,
)

MANIFEST = FIXTURE_DIR / "force_mechanics_reference.json"
ARRAYS = FIXTURE_DIR / "force_mechanics_reference.npz"
GENERATOR = FIXTURE_DIR / "generate_mech_phantoms.py"

EST = 5e3 / (1.0 - 0.3**2)


def _load_arrays():
    return dict(np.load(ARRAYS, allow_pickle=False))


def _curve_from_phantom(case) -> ForceCurve:
    """Materialize a phantom as a ForceCurve (FS-F1 model convention)."""
    k = K_SPRING

    def _seg(seg_type, direction, z, f):
        return ForceSegment(
            segment_type=seg_type, direction=direction, raw_height=z,
            raw_deflection=f / k, time=None, cycle=0, state="force_n",
            deflection=f / k, force=f, separation=None, metadata={},
        )

    retract_force = case.force[::-1].copy()
    return ForceCurve(
        segments=(
            _seg("extend", "forward", case.height, case.force),
            _seg("retract", "backward", case.height[::-1].copy(), retract_force),
        ),
        calibration=Calibration(
            invols=3e-8, spring_constant=k, method="thermal",
            temperature=300, provenance={},
        ),
        position=None, index=0, metadata={},
    )


def _prepared(case):
    return prepare_force_curve(_curve_from_phantom(case))


# ---------------------------------------------------------------------------
# fixture integrity
# ---------------------------------------------------------------------------


def test_fixture_regeneration_deterministic() -> None:
    """The committed reference files are regenerated byte-identically."""
    out1 = Path("/tmp/opencode") / f"mech_gen_{np.random.default_rng(0).integers(2**31)}_a"
    out2 = Path("/tmp/opencode") / f"mech_gen_{np.random.default_rng(0).integers(2**31)}_b"
    out1.mkdir(parents=True, exist_ok=True)
    out2.mkdir(parents=True, exist_ok=True)
    try:
        subprocess.run(
            [sys.executable, str(GENERATOR), str(out1)], check=True, capture_output=True
        )
        subprocess.run(
            [sys.executable, str(GENERATOR), str(out2)], check=True, capture_output=True
        )
        for name in ("force_mechanics_reference.json", "force_mechanics_reference.npz"):
            assert (out1 / name).read_bytes() == (out2 / name).read_bytes()
            assert (out1 / name).read_bytes() == (FIXTURE_DIR / name).read_bytes()
    finally:
        import shutil

        shutil.rmtree(out1, ignore_errors=True)
        shutil.rmtree(out2, ignore_errors=True)


def test_phantom_geometry_constraints() -> None:
    """Every phantom has monotone height and separation and a consistent
    contact index (FS-F1 eligibility gate and work integral acceptance)."""
    cases = generate_phantoms()
    arrays = _load_arrays()
    manifest = json.loads(MANIFEST.read_text())
    for cid, case in sorted(cases.items()):
        assert np.all(np.diff(case.height) > 0), cid
        assert np.all(np.diff(case.separation) > 0), cid
        assert np.all(np.isfinite(case.height)) and np.all(np.isfinite(case.force)), cid
        assert case.force.shape == case.height.shape, cid
        assert 0 <= case.contact_index < len(case.height), cid
        # disk copies match the live generation and the manifest truth
        assert np.array_equal(arrays[f"{cid}_height"], case.height), cid
        assert np.array_equal(arrays[f"{cid}_force"], case.force), cid
        assert manifest["cases"][cid]["truth"] == case.truth, cid


def test_clean_cases_have_zero_pre_contact_force() -> None:
    """Clean (noise-free, offset-free) phantoms carry zero pre-contact
    force so the FS-F1 baseline correction cannot subtract model signal."""
    cases = generate_phantoms()
    for cid in ("M01", "M02", "M03", "M04", "M05", "M09", "M11", "M12",
                "M15", "M16"):
        case = cases[cid]
        pre = slice(0, max(case.contact_index - 5, 0))
        assert np.all(np.abs(case.force[pre]) < 1e-14), cid


# ---------------------------------------------------------------------------
# analytical oracle parity
# ---------------------------------------------------------------------------


def test_oracle_forward_equations_parity() -> None:
    """The production forward model reproduces the independent oracle."""
    d = np.linspace(1e-9, 1e-6, 97)
    assert np.allclose(
        forward_model("hertz_sphere", d, {"E": 5e3, "R": 1e-6, "poisson": 0.3}),
        forward_hertz(d, EST, 1e-6), rtol=1e-12)
    assert np.allclose(
        forward_model("sneddon_cone", d,
                      {"E": 5e3, "alpha": math.radians(20.0), "poisson": 0.3}),
        forward_sneddon(d, EST, math.radians(20.0)), rtol=1e-12)
    assert np.allclose(
        forward_model("flat_punch", d, {"E": 5e3, "R": 1e-6, "poisson": 0.3}),
        forward_punch(d, EST, 1e-6), rtol=1e-12)
    assert np.allclose(
        forward_model("dmt", d, {"E": 5e3, "R": 1e-6, "poisson": 0.3, "F_adh": 2e-9}),
        forward_dmt(d, EST, 1e-6, 2e-9), rtol=1e-9, atol=1e-13)
    assert np.allclose(
        forward_model("jkr", d, {"E": 5e3, "R": 1e-6, "poisson": 0.3, "w": 1e-3}),
        forward_jkr(d, EST, 1e-6, 1e-3), rtol=1e-9, atol=1e-13)


def test_jkr_reduces_to_hertz_without_adhesion() -> None:
    d = np.linspace(1e-8, 1e-6, 50)
    jkr = forward_model("jkr", d, {"E": 5e3, "R": 1e-6, "poisson": 0.3, "w": 0.0})
    hertz = forward_model("hertz_sphere", d, {"E": 5e3, "R": 1e-6, "poisson": 0.3})
    assert np.allclose(jkr, hertz, rtol=1e-6)


# ---------------------------------------------------------------------------
# phantom truth recovery through the full stack
# ---------------------------------------------------------------------------


def test_clean_hertz_family_recovery() -> None:
    """Clean hertz-family phantoms recover E within a few percent; the
    residual bias is the FS-F1 contact precision (~1 sample = 1.5e-8 m)."""
    cases = generate_phantoms()
    fits = {
        "M01": (fit_hertz_sphere, {"tip_radius": 1e-6}),
        "M02": (fit_sneddon_cone, {"half_angle": math.radians(20.0)}),
        "M03": (fit_flat_punch, {"punch_radius": 1e-6}),
        "M09": (fit_hertz_sphere, {"tip_radius": 1e-6}),
        "M12": (fit_hertz_sphere, {"tip_radius": 1e-6}),
    }
    for cid, (fn, kwargs) in fits.items():
        prepared = _prepared(cases[cid])
        ind = compute_indentation(prepared)
        window = select_contact_fit_window(prepared, ind, min_indentation=0.0,
                                           min_points=10)
        fit = fn(prepared, ind, window, **kwargs)
        assert fit.success, cid
        rel = abs(fit.parameters["E"] - 5e3) / 5e3
        assert rel < 0.05, (cid, rel)


def test_noisy_recovery_within_ten_percent() -> None:
    """Noisy phantoms recover E within 10% (noise 2e-12 N on ~1e-8..1e-5 N
    force branches; the residual bias is contact-precision dominated)."""
    cases = generate_phantoms()
    for cid in ("M06", "M10", "M13"):
        prepared = _prepared(cases[cid])
        ind = compute_indentation(prepared)
        window = select_contact_fit_window(prepared, ind, min_indentation=0.0,
                                           min_points=10)
        fit = fit_hertz_sphere(prepared, ind, window, tip_radius=1e-6)
        rel = abs(fit.parameters["E"] - 5e3) / 5e3
        assert rel < 0.10, (cid, rel)


def test_offset_slope_robustness() -> None:
    """A small force offset and residual slope perturb E only slightly."""
    case = generate_phantoms()["M08"]
    prepared = _prepared(case)
    ind = compute_indentation(prepared)
    window = select_contact_fit_window(prepared, ind, min_indentation=0.0, min_points=10)
    fit = fit_sneddon_cone(prepared, ind, window,
                           half_angle=math.radians(20.0))
    rel = abs(fit.parameters["E"] - 5e3) / 5e3
    assert rel < 0.05, rel


def test_adhesive_recovery_trimmed_windows() -> None:
    """DMT/JKR recovery on snap-in curves, with windows trimmed past the
    snap-in region.  The FS-F1 contact ensemble lands up to ~10 samples off
    on snap-in curves; the honest recovery bounds are documented here."""
    cases = generate_phantoms()
    prepared = _prepared(cases["M04"])
    ind = compute_indentation(prepared)
    window = select_contact_fit_window(prepared, ind, min_indentation=1.8e-7,
                                       min_points=10)
    fit = fit_dmt(prepared, ind, window, tip_radius=1e-6)
    assert abs(fit.parameters["E"] - 5e3) / 5e3 < 0.30
    assert abs(fit.parameters["F_adh"] - 2e-9) < 1.5e-9

    prepared = _prepared(cases["M05"])
    ind = compute_indentation(prepared)
    window = select_contact_fit_window(prepared, ind, min_indentation=2e-7,
                                       min_points=10)
    fit = fit_jkr(prepared, ind, window, tip_radius=1e-6)
    assert fit.success
    assert abs(fit.parameters["E"] - 5e3) / 5e3 < 0.20
    assert abs(fit.parameters["w"] - 1e-3) / 1e-3 < 0.30


def test_misspecification_detected_by_comparison() -> None:
    """Cone data fitted with a hertz model is flagged by the model
    comparison: the cone model wins with near-unit weight."""
    case = generate_phantoms()["M15"]
    prepared = _prepared(case)
    ind = compute_indentation(prepared)
    window = select_contact_fit_window(prepared, ind, min_indentation=0.0, min_points=10)
    cmp = compare_contact_models(prepared, ind, window, tip_radius=1e-6)
    assert cmp.recommended_model == "sneddon_cone"
    assert cmp.weights["sneddon_cone"] > 0.9
    assert not cmp.ambiguous


# ---------------------------------------------------------------------------
# failure witnesses (typed, never silent)
# ---------------------------------------------------------------------------


def test_saturation_witness() -> None:
    """A saturated curve is flagged SATURATED_SIGNAL by the FS-F1 quality
    gate; the fit result stays biased and the flag is never dropped."""
    case = generate_phantoms()["M11"]
    prepared = _prepared(case)
    assert "SATURATED_SIGNAL" in prepared.quality.failure_reasons
    ind = compute_indentation(prepared)
    window = select_contact_fit_window(prepared, ind, min_indentation=0.0, min_points=10)
    fit = fit_hertz_sphere(prepared, ind, window, tip_radius=1e-6)
    # the saturated tail biases the modulus well outside the clean band
    assert abs(fit.parameters["E"] - 5e3) / 5e3 > 0.05


def test_shallow_noisy_curve_fails_typed() -> None:
    """A shallow, noisy indentation cannot support the FS-F1 contact
    ensemble: preparation raises a typed CONTACT_NOT_FOUND failure."""
    case = generate_phantoms()["M17"]
    with pytest.raises(ForceFoundationError) as ei:
        _prepared(case)
    assert "CONTACT_NOT_FOUND" in str(ei.value)


def test_flat_curve_fails_typed() -> None:
    """A flat curve (no contact branch) fails preparation typed."""
    case = generate_phantoms()["M18"]
    with pytest.raises(ForceFoundationError) as ei:
        _prepared(case)
    assert "CONTACT_NOT_FOUND" in str(ei.value)


# ---------------------------------------------------------------------------
# reliability determinism
# ---------------------------------------------------------------------------


def test_sensitivity_and_bootstrap_deterministic() -> None:
    """The sensitivity multiverse and the residual bootstrap are
    deterministic replays on the frozen phantom."""
    case = generate_phantoms()["M01"]
    prepared = _prepared(case)
    ind = compute_indentation(prepared)
    window = select_contact_fit_window(prepared, ind, min_indentation=0.0, min_points=10)
    a = analyze_force_fit_sensitivity(prepared, tip_radius=1e-6)
    b = analyze_force_fit_sensitivity(prepared, tip_radius=1e-6)
    assert a.parameter_multiverse == b.parameter_multiverse
    assert a.n_configurations <= 512
    assert a.n_skipped == b.n_skipped

    boot_a = bootstrap_force_fit((prepared, ind, window, "hertz_sphere"),
                                 samples=60, seed=11, tip_radius=1e-6)
    boot_b = bootstrap_force_fit((prepared, ind, window, "hertz_sphere"),
                                 samples=60, seed=11, tip_radius=1e-6)
    assert boot_a.parameter_samples == boot_b.parameter_samples
    assert boot_a.n_success >= 0.8 * 60
    # the diagnostic status is a policy, not a probability
    fit = fit_hertz_sphere(prepared, ind, window, tip_radius=1e-6)
    diag = diagnose_force_fit(fit, sensitivity=a, bootstrap=boot_a)
    assert diag.summary_status in ("ok", "review")


# ---------------------------------------------------------------------------
# volume mechanics end-to-end
# ---------------------------------------------------------------------------


def test_volume_mechanics_end_to_end() -> None:
    """The volume mapping runs the full stack per curve; failed curves stay
    explicitly masked and nothing is silently dropped.  The synthetic
    volume mixes clean, noisy, contact-offset, adhesive and failed curves:
    a vertical proof, not an experimental map validation."""
    cases = generate_phantoms()
    curves = [_curve_from_phantom(cases[cid])
              for cid in ("M01", "M06", "M09", "M04", "M18")]
    volume = ForceVolume.from_curves(curves, grid_shape=(1, 5), x_range=1e-6,
                                     y_range=5e-6)
    res = fit_force_volume_mechanics(volume, tip_radius=1e-6, min_points=20)
    assert res.modulus_map.shape == (5,)
    assert res.failed_mask[4]  # M18 flat curve is explicitly masked
    assert not res.failed_mask[:4].any()
    assert np.isfinite(res.modulus_map[:4]).all()
    assert res.modulus_map[0] > 0.0
    assert res.provenance["n_failed"] == 1
    assert res.provenance["deterministic"]
    assert res.provenance["failed_reasons"] == {4: "ForceFoundationError"}
    # mixed-model region: the cone curve must be mapped to the cone model
    mixed = ForceVolume.from_curves(
        [_curve_from_phantom(cases["M02"])], grid_shape=(1, 1), x_range=1e-6,
        y_range=1e-6)
    res2 = fit_force_volume_mechanics(
        mixed, tip_radius=1e-6, min_points=20,
        models=("hertz_sphere", "sneddon_cone"))
    assert res2.model_map[0] == "sneddon_cone"
    # replay is identical (NaN-safe: the failed curve stays NaN-masked)
    res3 = fit_force_volume_mechanics(volume, tip_radius=1e-6, min_points=20)
    np.testing.assert_array_equal(res.modulus_map, res3.modulus_map)
    np.testing.assert_array_equal(res.failed_mask, res3.failed_mask)


# ---------------------------------------------------------------------------
# external nanite overlap (black-box campaign, pinned in .reference/)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not NANITE_DIR.exists(),
    reason="evidencia externa (nanite) no disponible (gitignored)",
)
def test_external_nanite_contact_overlap() -> None:
    """The FS-F1 contact ensemble lands inside the nanite 4-method contact
    bracket on the shared P-case campaign (checked-in black-box outputs)."""
    campaign_input = NANITE_DIR / "campaign_input.json"
    campaign_output = NANITE_DIR / "campaign_output.json"
    assert campaign_input.exists() and campaign_output.exists()
    inp = json.loads(campaign_input.read_text())
    out = json.loads(campaign_output.read_text())
    by_id = {o["case_id"]: o for o in out}
    inside = 0
    prepared_count = 0
    for case in inp["cases"]:
        cid = case["case_id"]
        o = by_id[cid]
        nanite = [v for k, v in o.items() if k.startswith("contact_") and isinstance(v, int)]
        assert nanite, cid
        curve = _curve_from_phantom_arrays(
            np.asarray(case["approach_height"]), np.asarray(case["approach_force"]),
            np.asarray(case["retract_height"]), np.asarray(case["retract_force"]),
            case["spring_constant"],
        )
        try:
            prepared = prepare_force_curve(curve)
        except ForceFoundationError:
            continue  # witness: some P-cases fail preparation typed
        prepared_count += 1
        f1 = prepared.contact.selected.index
        if min(nanite) <= f1 <= max(nanite):
            inside += 1
    assert prepared_count >= 15, prepared_count
    assert inside == prepared_count, f"{inside}/{prepared_count}"


def _curve_from_phantom_arrays(za, fa, zr, fr, k) -> ForceCurve:
    def _seg(seg_type, direction, z, f):
        return ForceSegment(
            segment_type=seg_type, direction=direction, raw_height=z,
            raw_deflection=f / k, time=None, cycle=0, state="force_n",
            deflection=f / k, force=f, separation=None, metadata={},
        )

    return ForceCurve(
        segments=(_seg("extend", "forward", za, fa),
                  _seg("retract", "backward", zr, fr)),
        calibration=Calibration(invols=3e-8, spring_constant=k, method="thermal",
                                temperature=300, provenance={}),
        position=None, index=0, metadata={},
    )


# ---------------------------------------------------------------------------
# real-data characterization
# ---------------------------------------------------------------------------


def test_real_data_no_silent_garbage() -> None:
    """On the real NID spectroscopy set every curve either completes the
    FS-F2 stack or raises a typed failure; a successful fit must be finite."""
    from spmkit.core.io import load_force

    nid_path = (
        Path(__file__).resolve().parent / "fixtures" / "force_foundation" / "spectroscopy.nid"
    )
    assert nid_path.exists()
    vol = load_force(str(nid_path))
    completed = 0
    fitted = 0
    typed = 0
    for i in range(vol.n_curves):
        curve = vol.curve(i)
        ext = curve.extend
        if ext is None:
            continue
        z = np.asarray(ext.raw_height, dtype=np.float64)
        if not (z.size and np.all(np.diff(z) > 0)):
            continue
        try:
            prepared = prepare_force_curve(curve)
            completed += 1
            ind = compute_indentation(prepared)
            window = select_contact_fit_window(prepared, ind, min_points=10)
            fit = fit_hertz_sphere(prepared, ind, window, tip_radius=10e-9)
            assert fit.success
            assert np.isfinite(fit.parameters["E"])
            assert np.isfinite(fit.objective)
            fitted += 1
        except (ForceMechanicsError, ForceFoundationError):
            typed += 1
    assert completed + typed >= 1
    assert fitted >= 0
