"""Numerical kernels compatible with Gwyddion's Revolve Arc operation.

This module implements the numerical semantics of the Gwyddion 2.71
``arc-revolve`` process independently in NumPy.  It intentionally remains
separate from SPMKit's physical arc-revolution estimator because the two
operations use different radius, scaling, and boundary conventions.
"""

from __future__ import annotations

import math

import numpy as np
from numpy.typing import NDArray

FloatArray = NDArray[np.float64]


def _gwyddion_round_positive(value: object) -> int:
    """Round a finite non-negative scalar using ``floor(value + 0.5)``.

    Gwyddion's ``GWY_ROUND`` macro does not use bankers' rounding.  In
    particular, ``2.5`` becomes ``3`` and ``4.5`` becomes ``5``.
    """
    value_data = np.asarray(value)

    if (
        value_data.ndim != 0
        or not np.issubdtype(value_data.dtype, np.number)
        or np.iscomplexobj(value_data)
        or isinstance(value, (bool, np.bool_))
    ):
        raise TypeError("Gwyddion rounding requires a real scalar")

    numeric_value = float(value_data.item())

    if not math.isfinite(numeric_value):
        raise ValueError("Gwyddion rounding requires a finite scalar")

    if numeric_value < 0.0:
        raise ValueError("Gwyddion rounding requires a non-negative scalar")

    return math.floor(numeric_value + 0.5)


def _make_gwyddion_arc(
    radius: object,
    maxres: object,
) -> FloatArray:
    """Return the dimensionless arc generated by Gwyddion 2.71.

    Parameters
    ----------
    radius:
        Arc radius in samples, following Gwyddion's pixel-based convention.
    maxres:
        Maximum available profile resolution.  The generated half-width is
        ``GWY_ROUND(min(radius, maxres))``.

    Returns
    -------
    numpy.ndarray
        Read-only, symmetric ``float64`` arc with an odd number of samples.

    Notes
    -----
    The very-flat-arc polynomial is reproduced with the same operation order
    as the reference C implementation.  Values whose normalized offset
    exceeds one are clipped to one, matching Gwyddion's explicit branch.
    """
    radius_data = np.asarray(radius)

    if (
        radius_data.ndim != 0
        or not np.issubdtype(radius_data.dtype, np.number)
        or np.iscomplexobj(radius_data)
        or isinstance(radius, (bool, np.bool_))
    ):
        raise TypeError("Gwyddion arc radius must be a positive real scalar")

    radius_value = float(radius_data.item())

    if not math.isfinite(radius_value):
        raise ValueError("Gwyddion arc radius must be finite")

    if radius_value <= 0.0:
        raise ValueError("Gwyddion arc radius must be positive")

    maxres_data = np.asarray(maxres)

    if (
        maxres_data.ndim != 0
        or not np.issubdtype(maxres_data.dtype, np.integer)
        or isinstance(maxres, (bool, np.bool_))
    ):
        raise TypeError("Gwyddion arc maxres must be a positive integer")

    maxres_value = int(maxres_data.item())

    if maxres_value <= 0:
        raise ValueError("Gwyddion arc maxres must be positive")

    size = _gwyddion_round_positive(min(radius_value, maxres_value))
    arc = np.empty(2 * size + 1, dtype=np.float64)
    use_flat_arc_expansion = radius_value / 8.0 > maxres_value

    for offset in range(size + 1):
        normalized_offset = offset / radius_value

        if use_flat_arc_expansion:
            squared_offset = normalized_offset * normalized_offset
            height = (
                squared_offset
                / 2.0
                * (
                    1.0
                    + squared_offset
                    / 4.0
                    * (1.0 + squared_offset / 2.0)
                )
            )
        elif normalized_offset > 1.0:
            height = 1.0
        else:
            height = 1.0 - math.sqrt(
                1.0 - normalized_offset * normalized_offset
            )

        arc[size + offset] = height
        arc[size - offset] = height

    arc.setflags(write=False)
    return arc
