"""Typed failures for the FS-F4 single-molecule force spectroscopy batch."""

MISSING_RETRACT = "MISSING_RETRACT"
MISSING_TIME = "MISSING_TIME"
DUPLICATE_TIMESTAMPS = "DUPLICATE_TIMESTAMPS"
NONMONOTONIC_TIME = "NONMONOTONIC_TIME"
UNRESOLVED_TETHER_ZERO = "UNRESOLVED_TETHER_ZERO"
INVALID_REFERENCE_POLICY = "INVALID_REFERENCE_POLICY"
EMPTY_WINDOW = "EMPTY_WINDOW"
INSUFFICIENT_POINTS = "INSUFFICIENT_POINTS"
INVALID_MODEL_PARAMETER = "INVALID_MODEL_PARAMETER"
POLYMER_SINGULARITY = "POLYMER_SINGULARITY"
OPTIMIZATION_FAILED = "OPTIMIZATION_FAILED"
NONFINITE_INPUT = "NONFINITE_INPUT"
NO_EVENTS = "NO_EVENTS"
EVENT_NEAR_BOUNDARY = "EVENT_NEAR_BOUNDARY"
UNDEFINED_MEDIAN = "UNDEFINED_MEDIAN"
INSUFFICIENT_EVENTS = "INSUFFICIENT_EVENTS"
KINETIC_DOMAIN = "KINETIC_DOMAIN"
CENSORING_INVALID = "CENSORING_INVALID"
IDENTIFIABILITY_LIMITED = "IDENTIFIABILITY_LIMITED"
PROTOCOL_MODEL_MISMATCH = "PROTOCOL_MODEL_MISMATCH"


class SmfsError(ValueError):
    """Typed FS-F4 failure with a machine-readable code."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
