"""Typed failures for the FS-F3 time-domain viscoelasticity batch."""

MISSING_TIME = "MISSING_TIME"
DUPLICATE_TIMESTAMPS = "DUPLICATE_TIMESTAMPS"
NONMONOTONIC_TIME = "NONMONOTONIC_TIME"
INSUFFICIENT_PROTOCOL = "INSUFFICIENT_PROTOCOL"
AMBIGUOUS_PROTOCOL = "AMBIGUOUS_PROTOCOL"
MISSING_CONTACT = "MISSING_CONTACT"
PROTOCOL_MODEL_MISMATCH = "PROTOCOL_MODEL_MISMATCH"
EMPTY_REGION = "EMPTY_REGION"
INVALID_RESPONSE = "INVALID_RESPONSE"
NONFINITE_RESPONSE = "NONFINITE_RESPONSE"
INVALID_MODEL_PARAMETER = "INVALID_MODEL_PARAMETER"
OPTIMIZATION_FAILED = "OPTIMIZATION_FAILED"
PRONY_DUPLICATE_TAU = "PRONY_DUPLICATE_TAU"
PRONY_NEGATIVE_TERM = "PRONY_NEGATIVE_TERM"
LEE_RADOK_NONMONOTONIC = "LEE_RADOK_NONMONOTONIC"
TING_HISTORY_UNAVAILABLE = "TING_HISTORY_UNAVAILABLE"
CURVE_NOT_FIT_ELIGIBLE = "CURVE_NOT_FIT_ELIGIBLE"
IDENTIFIABILITY_LIMITED = "IDENTIFIABILITY_LIMITED"
NO_VISCOELASTIC_FIT = "NO_VISCOELASTIC_FIT"


class ViscoelasticityError(ValueError):
    """Typed FS-F3 failure with a machine-readable code."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
