"""Typed failures for the FS-F2 force-mechanics batch."""

INVALID_INDENTATION = "INVALID_INDENTATION"
EMPTY_FIT_WINDOW = "EMPTY_FIT_WINDOW"
INSUFFICIENT_FIT_POINTS = "INSUFFICIENT_FIT_POINTS"
INVALID_RADIUS = "INVALID_RADIUS"
INVALID_ANGLE = "INVALID_ANGLE"
INVALID_POISSON_RATIO = "INVALID_POISSON_RATIO"
INVALID_ADHESION_PARAMETER = "INVALID_ADHESION_PARAMETER"
NONFINITE_INPUT = "NONFINITE_INPUT"
OPTIMIZATION_FAILED = "OPTIMIZATION_FAILED"
PARAMETER_AT_BOUND = "PARAMETER_AT_BOUND"
NONIDENTIFIABLE_MODEL = "NONIDENTIFIABLE_MODEL"
CONTACT_SENSITIVITY_HIGH = "CONTACT_SENSITIVITY_HIGH"
WINDOW_SENSITIVITY_HIGH = "WINDOW_SENSITIVITY_HIGH"
MODEL_AMBIGUOUS = "MODEL_AMBIGUOUS"
BOOTSTRAP_INSUFFICIENT_SUCCESS = "BOOTSTRAP_INSUFFICIENT_SUCCESS"
CURVE_NOT_FIT_ELIGIBLE = "CURVE_NOT_FIT_ELIGIBLE"


class ForceMechanicsError(ValueError):
    """Typed FS-F2 failure with a machine-readable code."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
